CREATE TABLE Locacao (
Id INT IDENTITY(1,1) PRIMARY KEY,
Nome NVARCHAR(200) NOT NULL,
Email NVARCHAR(150) NOT NULL,
Modelo NVARCHAR(100) NOT NULL,
Ano INT NOT NULL,
TempoAluguel NVARCHAR(50) NOT NULL,
Data DATETIME2 NOT NULL,
DataInsercao DATETIME2 DEFAULT GETDATE()
);